name: winmart
description: A Vietnamese grocery shopping app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  page_transition: ^2.0.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - images/welcome.png
    - images/hamburger.png
    - images/pasta.png
    - images/akara.png
    - images/strawberry.png
    - images/coca-cola.png
    - images/lemonade.png
    - images/vodka.png
    - images/tequila.png
    - images/pancake.png
    - images/sandwich.png
    - images/burger.png
    - images/fish_and_chips.png
    - images/pizza.png
    - images/cheese_cake.png
    - images/hot_dog.png
    - images/fried_chicken.png
    - images/french_fries.png
    - images/milkshake.png
    - images/onion_rings.png
    - images/ice_cream.png
    - images/yogurt.png
    - images/spring_rolls.png
    - images/fried_tofu.png
    - images/coffee.png
    - images/tea.png
    - images/hot_chocolate.png
    - images/herbal_tea.png
    - images/latte.png
    - images/carrot.png
    - images/broccoli.png
    - images/spinach.png
    - images/tomato.png
    - images/cucumber.png

  fonts:
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf
